import "./terms.scss";

export default function TermsPage() {
  return (
    <div className="terms-container">
        <div className="terms-content">
      <h1 className="title">Terms And Conditions</h1>
      <p className="date">Effective Date: March 12, 2026</p>

      <section>
        <h1>1. INTRODUCTION AND ACCEPTANCE</h1>
        <p className="terms-p">
          <strong>1.1 {"  "}</strong>These Terms and Conditions (“Terms”) govern access to and use of the Synergetics Marketplace (“Platform”), 
          operated by UnifyGPT Inc. d/b/a Synergetics (“Synergetics,” “we,” “us,” or “our”). By accessing, registering, 
          listing, purchasing, or otherwise using the Platform, you agree to be bound by these Terms.
        </p>
        <p className="terms-p">
          <strong>1.2 {"  "}</strong>These Terms apply to all users, including without limitation sellers, buyers, developers, and visitors 
          (collectively, “Users”). If you do not agree to these Terms, you must not use the Platform.
        </p>
      </section>

      <section>
        <h1>2. DEFINITIONS</h1>
        <ul>
          <li>
            <strong>Digital Assets:</strong> Any products or services made available on the Platform, 
            including but not limited to AI agents, avatars, skills, software modules, integrations, 
            wearables, datasets, and related content.
          </li>
          <li>
            <strong>Seller:</strong> Any User who lists or offers Digital Assets on the Platform.
          </li>
          <li>
            <strong>Buyer:</strong> Any User who purchases, subscribes to, or otherwise uses Digital Assets.
          </li>
          <li>
            <strong>User Content:</strong> Any data, content, or materials uploaded, submitted, or generated by Users.
          </li>
        </ul>
      </section>

      <section>
        <h1>3. ROLE OF SYNERGETICS</h1>
        <p className="terms-p">
          <strong>3.1 {"  "}</strong>Synergetics provides a technology platform that enables Sellers to list and distribute Digital Assets 
          and Buyers to discover, purchase, and use such Digital Assets.
        </p>
        <p className="terms-p">
          <strong>3.2 {"  "}</strong>Synergetics is not the creator, owner, or seller of third-party Digital Assets and is not a party to 
          any agreement between Buyers and Sellers. Synergetics does not control, endorse, or guarantee the quality, 
          legality, or functionality of Digital Assets.
        </p>
      </section>

      <section>
        <h1>4. ACCOUNT REGISTRATION AND SECURITY</h1>
        <p className="terms-p">
          <strong>4.1 {"  "}</strong>Users may be required to create an account. You agree to provide accurate and complete information and 
          to maintain the confidentiality of your account credentials.
        </p>
        <p className="terms-p">
          <strong>4.2 {"  "}</strong>You are responsible for all activities under your account. Synergetics is not liable for unauthorized 
          access resulting from your failure to safeguard your credentials.
        </p>
      </section>

      <section>
        <h1>5. SELLER OBLIGATIONS</h1>
        <p className="terms-p"><strong>5.1 {"  "}</strong>Sellers represent and warrant that:</p>
        <ul>
          <li>They have all necessary rights, licenses, and permissions to offer Digital Assets.</li>
          <li>Their Digital Assets do not infringe any intellectual property or proprietary rights.</li>
          <li>Their Digital Assets comply with applicable laws and regulations, including privacy and data protection laws.</li>
          <li>They will provide accurate descriptions and any applicable licensing or service terms.</li>
        </ul>
        <p className="terms-p">
          <strong>5.2 {"  "}</strong>Sellers are solely responsible for support, maintenance, and performance of their Digital Assets.
        </p>
      </section>

      <section>
        <h1>6. BUYER OBLIGATIONS</h1>
        <p className="terms-p"><strong>6.1 {"  "}</strong>Buyers agree:</p>
        <ul>
          <li>To pay all applicable fees and charges.</li>
          <li>To use Digital Assets in compliance with applicable laws and any applicable licenses.</li>
          <li>Not to misuse the Platform, including generating unlawful or harmful content.</li>
        </ul>
        <p className="terms-p">
          <strong>6.2 {"  "}</strong>Buyers acknowledge that Digital Assets may be subject to separate license terms provided by Sellers.
        </p>
      </section>

      <section>
        <h1>7. FEES AND PAYMENTS</h1>
        <p className="terms-p">
          <strong>7.1 {"  "}</strong>Synergetics may charge transaction fees, subscription fees, or other charges. All fees are non-refundable unless 
          otherwise stated.
        </p>
        <p className="terms-p">
          <strong>7.2 {"  "}</strong>Payments may be processed via fiat currency or platform-based tokens. Token balances are non-transferable 
            except as expressly permitted.
        </p>
      </section>

      <section>
        <h1>8. INTELLECTUAL PROPERTY</h1>
        <p className="terms-p"><strong>8.1 {"  "}</strong>Synergetics retains all rights in and to the Platform.</p>
        <p className="terms-p"><strong>8.2 {"  "}</strong>Sellers retain ownership of their Digital Assets, subject to licenses granted to Buyers.</p>
        <p className="terms-p">
          <strong>8.3 {"  "}</strong>Buyers receive a limited, non-exclusive, non-transferable license to use Digital Assets in accordance with applicable terms.
        </p>
      </section>

      <section>
        <h1>9. DISCLAIMERS</h1>
        <div>
          <p className="terms-p">
            <strong>9.1 {"  "}</strong>THE PLATFORM AND ALL DIGITAL ASSETS ARE PROVIDED “AS IS” AND “AS AVAILABLE.”
          </p>
          <p className="terms-p">
            <strong>9.2 {"  "}</strong>SYNERGETICS DISCLAIMS ALL WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
          <p className="terms-p">
            <strong>9.3 {"  "}</strong>SYNERGETICS DOES NOT WARRANT THAT DIGITAL ASSETS WILL BE ERROR-FREE, ACCURATE, OR RELIABLE, INCLUDING OUTPUT 
            GENERATED BY AI SYSTEMS.
          </p>
        </div>
      </section>

      <section>
        <h1>10. LIMITATION OF LIABILITY</h1>
        <p className="terms-p">
          <strong>10.1 {"  "}</strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SYNERGETICS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
          CONSEQUENTIAL, OR PUNITIVE DAMAGES.
        </p>
        <p className="terms-p">
            <strong>10.2 {"  "}</strong>SYNERGETICS’ TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNTS PAID BY THE USER TO SYNERGETICS IN THE 
            TWELVE (12) MONTHS PRECEDING THE CLAIM.
        </p>
      </section>

      <section>
        <h1>11. INDEMNIFICATION</h1>
        <p className="terms-p">
          <strong>11.1 {"  "}</strong>You agree to indemnify and hold harmless Synergetics and its affiliates from any claims arising out of:
        </p>
        <ul>
          <li>Your use of the Platform;</li>
          <li>Your violation of these Terms;</li>
          <li>Your infringement of any rights of a third party.</li>
        </ul>
      </section>

      <section>
        <h1>12. SUSPENSION AND TERMINATION</h1>
        <p className="terms-p">
          <strong>12.1 {"  "}</strong>Synergetics may suspend or terminate access to the Platform at its discretion, including for violations of these Terms.
        </p>
        <p className="terms-p">
          <strong>12.2 {"  "}</strong>Upon termination, your right to use the Platform ceases immediately.
        </p>
      </section>

      <section>
        <h1>13. PRIVACY AND DATA</h1>
        <p className="terms-p">
          <strong>13.1 {"  "}</strong>Use of the Platform is subject to Synergetics’ Privacy Policy.
        </p>
        <p className="terms-p">
          <strong>13.2 {"  "}</strong>Users are responsible for ensuring compliance with applicable data protection laws when using or deploying Digital Assets.
        </p>
      </section>

      <section>
        <h1>14. GOVERNING LAW AND DISPUTE RESOLUTION</h1>
        <p className="terms-p">
          <strong>14.1 {"  "}</strong>These Terms are governed by the laws of the State of California.
        </p>
        <p className="terms-p">
          <strong>14.2 {"  "}</strong>Any disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
        </p>
      </section>

      <section>
        <h1>15. MODIFICATIONS</h1>
        <p className="terms-p">
          <strong>15.1 {"  "}</strong>Synergetics reserves the right to modify these Terms at any time. Continued use of the Platform constitutes acceptance of updated Terms.
        </p>
      </section>

      <section>
        <h1>16. ENTIRE AGREEMENT</h1>
        <p className="terms-p">
          <strong>16.1 {"  "}</strong>These Terms constitute the entire agreement between you and Synergetics regarding the Platform.
        </p>
      </section>

      <div className="footer-note">
        By clicking "I Agree" or by using the Synergetics Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms.
      </div>
      </div>
    </div>
  );
}