
export const KNOWLEDGEBASE="knowledgebase"
export const FILE="file"
export const QNA="QNA"
export const USER_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibW9oaXQuc0B3ZWJ0aWdhLmNvbSIsInJvbGUiOiJCVVlFUiIsImlhdCI6MTc1NTU3OTM2MiwiZXhwIjoxNzU1NjY1NzYyfQ.wXDqIj5wn0KLYvYnAxDaNQQjENVZpnEyUEIlOroQRI0"
// "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibW9oaXQuc0B3ZWJ0aWdhLmNvbSIsInJvbGUiOiJCVVlFUiIsImlhdCI6MTc1MzA0MDI2OSwiZXhwIjoxNzUzMTI2NjY5fQ.GGkHTD8pnRROiibgPMp_axhSG2OjPqICvUAtPRpoZhg"